### ISSUE TITLE
Buy Service Function

### ISSUE THREAD

**Issue by ste7een** [EnabApp/APP-AppStore#5]
Buy service completely done in ~~supabase but when we use it we get

**Could not find the public.buyService(service_id, user_id) function or the public.buyService function with a single unnamed json or jsonb parameter in the schema cache**

![Image](https://user-images.githubusercontent.com/64214350/186617020-15c2443e-587d-418e-8767-00727074a007.png)

**Comment by ste7een** [comment]
Error fixed . 
and we need to do : 

- [ ] alert for actions ( buy done or errors ) 
- [ ] Loading button

**Comment by Gruce** [comment]
Have you fixed this issue?

**Comment by ste7een** [comment]
Hi @Gruce 
I fixed the problem and revised it and it will be launched with the next version.
Thank you
