### ISSUE TITLE
Owned Services

### ISSUE THREAD

**Issue by ste7een** [EnabApp/APP-AppStore#6]
Get owned services and show  it in **my apps** component as extended service for each app  .

**Comment by Gruce** [comment]
Hello @ste7een ,
Now you have getters in `App Manager` that can get all your owned services. You have also in `App Model` (app object) the ability to get all services of the individual app using `app.getOwnedServices`.

Thank you

**Comment by ste7een** [comment]
Hi @Gruce 
I completed all structure by `appManager` without any bugs .
Thank you .
