### ISSUE TITLE
Buy apps and services structure

### ISSUE THREAD

**Issue by ste7een** [EnabApp/APP-AppStore#9]
Hi @everyone 👋

I am wondering about purchases, if the user subscribes to the application and also buys an  service inside this app , at the end of the subscription will he subscribe again to the service or will he get it forever 🤔 .

Please leave a comment below that matches with our vision 🥰 .

**Comment by william-iq397** [comment]
Hi Muntazer, indeed the App will last forever when buy it.
thanks for looking to our product.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Montazer Malik ***@***.***>
Sent: Friday, August 26, 2022 9:11:50 AM
To: EnabApp/APP-AppStore ***@***.***>
Cc: william-iq397 ***@***.***>; Assign ***@***.***>
Subject: [EnabApp/APP-AppStore] Buy apps and services structure (Issue #9)


Hi @everyone<https://github.com/everyone> 👋

I am wondering about purchases, if the user subscribes to the application and also buys an service inside this app , at the end of the subscription will he subscribe again to the service or will he get it forever 🤔 .

Please leave a comment below that matches with our vision 🥰 .

**Comment by Gruce** [comment]
Hello @ste7een,

I prefer that application lasts forever but services has two options (forever services and period services).
Also I prefer we could work on a better solution which it is pay-as-you-cost which he could get anything now but you have to pay to continue and that gives the ability to the users to try and work on the system freely and become more satisfied when he pays. We can also make the system cuts and checks every X day in a month so those users whose not paying could be given a week before suspend his account.

Thank you.

**Comment by i1Zeus** [comment]
@ste7een ,sup!

The way I see it.... u can give him a trail , he might use our free services form free than after X amount of days he have to pay us ,  not sure how much tho...

**Comment by a7med3bd** [comment]
Hi @ste7een 
As for the applications, I prefer to buy them once permanently.
As for the services, it depends on the type of service. There are basic services that are free, and they determine the price of the application (the price of the application depends on the permanent free services)
As for the additional paid services that he uses, they are in the form of monthly and yearly subscriptions.
With the opportunity to try paid services for a week when purchasing the application, for example.

**Comment by ste7een** [comment]
Hello everyone 
Thank you all. I have really benefited from your suggestions and will be inspired by some ideas from your suggestions and will work on them as soon as they are completed. This process is very, very important as it is the basis of operations and strategies that determine the income and method of profit in this project. 
Thank you all again.
@Gruce @william-iq397 @i1Zeus @a7med3bd
